/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.pdfrenderer;

import org.appcelerator.kroll.KrollProxy;

import android.graphics.pdf.PdfRenderer.Page;

public class PageProxy extends KrollProxy {
	public Page page;

	public PageProxy(Page page) {
		super();
		this.page = page;
	}

	public Page getPage() {
		return page;
	}

}
